In [173]:
import pandas as pd
import glob

# Ruta base donde se encuentran los archivos
file_path_base = r'C:\Users\Eduardo\Desktop\HACKATONRIMAC\EPS_PRESTACION_2022_'

# Lista para almacenar todos los DataFrames de los archivos
dfs = []

# Iterar sobre los 8 archivos
for i in range(1, 9):
    file_path = file_path_base + str(i) + '_v1.csv'
    df = pd.read_csv(file_path, encoding='latin1')
    dfs.append(df)

# Concatenar todos los DataFrames en uno solo
df_concatenated = pd.concat(dfs, ignore_index=True)

# Mostrar el DataFrame resultante
df_concatenated

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_27656\2334255060.py:13: DtypeWarning: Columns (8,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin1')

,NUMEROEXPEDIENTELIQUIDACION,CODIGO_IAFAS,RUCPRESTADOR,CODIGOSUNASAIPRESS,TIPODOCUMENTO,NRODOCUMENTO_CRYPTO,FECHANACIMIENTOPACIENTE,SEXO,FECHA_FALL_RENIEC,CODIGOTITULAR_CRYPTO,...,GASTOCOBERTURA04,GASTOCOBERTURA9,COPAGOFIJO,COPAGOVARIABLE,GASTONOCUBIERTO,TOTAL_GASTOPRESENTADOS,TOTALDEGASTOSDESCONTADOS,TOTALLIQUIDADOSIN_IGV,TOTAL_PAGADOSINIGV,PERIODOENVIO
0,3834427100002,2,20228319768,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29 00:00:00,0,NaN,877FDA2E617279F63A02451A28291CEA9738A018,...,0.0,0.0,25.0,5.66,0.0,0.00,30.7,-30.66,91.07,202211
1,3834427000002,2,20228319768,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29 00:00:00,0,NaN,877FDA2E617279F63A02451A28291CEA9738A018,...,0.0,0.0,150.0,21.78,0.0,0.00,171.8,-171.78,350.64,202211
2,3723736200002,2,20228319768,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29 00:00:00,0,NaN,877FDA2E617279F63A02451A28291CEA9738A018,...,0.0,0.0,30.0,32.79,0.0,377.92,62.8,315.13,315.13,202207
3,3735095200003,2,20228319768,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29 00:00:00,0,NaN,877FDA2E617279F63A02451A28291CEA9738A018,...,0.0,0.0,30.0,15.75,0.0,207.50,45.8,161.75,161.75,202209
4,3822502000002,2,20228319768,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29 00:00:00,0,NaN,877FDA2E617279F63A02451A28291CEA9738A018,...,0.0,0.0,0.0,11.47,0.0,50.85,11.5,39.38,184.88,202211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422813,22-00602302,27,20510931514,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26 00:00:00,0,NaN,ACC4C5FD7C097AB0146766ABC26FA6DFE3BEEEF3,...,0.0,0.0,0.0,0.00,0.0,50.00,0.0,50.00,59.00,202208
7422814,22-00563955,27,20510931514,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26 00:00:00,0,NaN,ACC4C5FD7C097AB0146766ABC26FA6DFE3BEEEF3,...,0.0,0.0,0.0,0.00,0.0,50.00,0.0,50.00,124.60,202207
7422815,22-00451291,27,20510931514,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26 00:00:00,0,NaN,ACC4C5FD7C097AB0146766ABC26FA6DFE3BEEEF3,...,0.0,0.0,0.0,0.00,0.0,173.81,0.0,173.81,205.10,202206
7422816,22-00513566,27,20510931514,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26 00:00:00,0,NaN,ACC4C5FD7C097AB0146766ABC26FA6DFE3BEEEF3,...,0.0,0.0,0.0,0.00,0.0,218.13,0.0,218.13,322.99,202206
7422817,22-00433532,27,20510931514,990014C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26 00:00:00,0,NaN,ACC4C5FD7C097AB0146766ABC26FA6DFE3BEEEF3,...,0.0,0.0,0.0,0.00,0.0,405.40,0.0,405.40,524.86,202205

In [174]:
df=df_concatenated

In [175]:
ruc_to_eps = {
    '20431115825': 'Pacífico EPS',
    '20517182673': 'Mafre EPS',
    '20601978572': 'Positiva EPS',
    '20523470761': 'Sanitas EPS',
    '20414955020': 'Rimac EPS'
}

# Función para mapear RUCPRESTADOR a EPS
def get_eps(ruc):
    return ruc_to_eps.get(str(ruc), "Otro")

# Crear la nueva columna 'EPS'
df['EPS'] = df['RUCPRESTADOR'].apply(get_eps)

# Reordenar columnas para colocar 'EPS' después de 'RUCPRESTADOR'
cols = df.columns.tolist()
ruco_index = cols.index('RUCPRESTADOR')
cols.insert(ruco_index + 1, cols.pop(cols.index('EPS')))
df = df[cols]

In [176]:
# Definir la fecha de referencia
fecha_referencia = pd.to_datetime('2022-01-01')

# Convertir la columna FECHANACIMIENTOPACIENTE a datetime
df['FECHANACIMIENTOPACIENTE'] = pd.to_datetime(df['FECHANACIMIENTOPACIENTE'])

# Calcular la edad
df['EDAD'] = fecha_referencia.year - df['FECHANACIMIENTOPACIENTE'].dt.year - (
    (fecha_referencia.month < df['FECHANACIMIENTOPACIENTE'].dt.month) | 
    ((fecha_referencia.month == df['FECHANACIMIENTOPACIENTE'].dt.month) & (fecha_referencia.day < df['FECHANACIMIENTOPACIENTE'].dt.day))
)
df

,NUMEROEXPEDIENTELIQUIDACION,CODIGO_IAFAS,RUCPRESTADOR,EPS,CODIGOSUNASAIPRESS,TIPODOCUMENTO,NRODOCUMENTO_CRYPTO,FECHANACIMIENTOPACIENTE,SEXO,FECHA_FALL_RENIEC,...,GASTOCOBERTURA9,COPAGOFIJO,COPAGOVARIABLE,GASTONOCUBIERTO,TOTAL_GASTOPRESENTADOS,TOTALDEGASTOSDESCONTADOS,TOTALLIQUIDADOSIN_IGV,TOTAL_PAGADOSINIGV,PERIODOENVIO,EDAD
0,3834427100002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,NaN,...,0.0,25.0,5.66,0.0,0.00,30.7,-30.66,91.07,202211,33
1,3834427000002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,NaN,...,0.0,150.0,21.78,0.0,0.00,171.8,-171.78,350.64,202211,33
2,3723736200002,2,20228319768,Otro,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,NaN,...,0.0,30.0,32.79,0.0,377.92,62.8,315.13,315.13,202207,33
3,3735095200003,2,20228319768,Otro,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,NaN,...,0.0,30.0,15.75,0.0,207.50,45.8,161.75,161.75,202209,33
4,3822502000002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,NaN,...,0.0,0.0,11.47,0.0,50.85,11.5,39.38,184.88,202211,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422813,22-00602302,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,NaN,...,0.0,0.0,0.00,0.0,50.00,0.0,50.00,59.00,202208,25
7422814,22-00563955,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,NaN,...,0.0,0.0,0.00,0.0,50.00,0.0,50.00,124.60,202207,25
7422815,22-00451291,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,NaN,...,0.0,0.0,0.00,0.0,173.81,0.0,173.81,205.10,202206,25
7422816,22-00513566,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,NaN,...,0.0,0.0,0.00,0.0,218.13,0.0,218.13,322.99,202206,25
7422817,22-00433532,27,20510931514,Otro,990014C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,NaN,...,0.0,0.0,0.00,0.0,405.40,0.0,405.40,524.86,202205,25

In [177]:
df.insert(df.columns.get_loc('SEXO') + 1, 'SEXO_STR', df['SEXO'].map({1: 'MUJER', 0: 'HOMBRE'}))
df

,NUMEROEXPEDIENTELIQUIDACION,CODIGO_IAFAS,RUCPRESTADOR,EPS,CODIGOSUNASAIPRESS,TIPODOCUMENTO,NRODOCUMENTO_CRYPTO,FECHANACIMIENTOPACIENTE,SEXO,SEXO_STR,...,GASTOCOBERTURA9,COPAGOFIJO,COPAGOVARIABLE,GASTONOCUBIERTO,TOTAL_GASTOPRESENTADOS,TOTALDEGASTOSDESCONTADOS,TOTALLIQUIDADOSIN_IGV,TOTAL_PAGADOSINIGV,PERIODOENVIO,EDAD
0,3834427100002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,HOMBRE,...,0.0,25.0,5.66,0.0,0.00,30.7,-30.66,91.07,202211,33
1,3834427000002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,HOMBRE,...,0.0,150.0,21.78,0.0,0.00,171.8,-171.78,350.64,202211,33
2,3723736200002,2,20228319768,Otro,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,HOMBRE,...,0.0,30.0,32.79,0.0,377.92,62.8,315.13,315.13,202207,33
3,3735095200003,2,20228319768,Otro,0026079,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,HOMBRE,...,0.0,30.0,15.75,0.0,207.50,45.8,161.75,161.75,202209,33
4,3822502000002,2,20228319768,Otro,060841C,1,70D912FEFD17BE245512B5CD00D6703B24C13FD6,1988-08-29,0,HOMBRE,...,0.0,0.0,11.47,0.0,50.85,11.5,39.38,184.88,202211,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422813,22-00602302,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,HOMBRE,...,0.0,0.0,0.00,0.0,50.00,0.0,50.00,59.00,202208,25
7422814,22-00563955,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,HOMBRE,...,0.0,0.0,0.00,0.0,50.00,0.0,50.00,124.60,202207,25
7422815,22-00451291,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,HOMBRE,...,0.0,0.0,0.00,0.0,173.81,0.0,173.81,205.10,202206,25
7422816,22-00513566,27,20510931514,Otro,980021C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,HOMBRE,...,0.0,0.0,0.00,0.0,218.13,0.0,218.13,322.99,202206,25
7422817,22-00433532,27,20510931514,Otro,990014C,1,53BE83C886B70D05625BB3B36E95CF8323006BCB,1996-08-26,0,HOMBRE,...,0.0,0.0,0.00,0.0,405.40,0.0,405.40,524.86,202205,25

In [178]:
df.drop(columns=['NUMEROEXPEDIENTELIQUIDACION', 'SEXO', 'CODIGO_IAFAS', 'CODIGOSUNASAIPRESS',"TIPODOCUMENTO","FECHA_FALL_RENIEC","CODIGOTITULAR_CRYPTO"
,"CODIGOASEGURADO_CRYPTO","PERIODOENVIO","GASTOCOBERTURA04","GASTOCOBERTURA9","COPAGOFIJO","COPAGOVARIABLE","GASTONOCUBIERTO"
,"GASTOHONORARIOPROC","GASTOEXLAB","GASTOEXIMAG","GASTOFARMACIA","GASTOSERVCLINICO","GASTOOTROS","FECHAINGRESOHOSPITALARIO","FECHAEGRESOHOSPITALARIO",
"TOTAL_GASTOPRESENTADOS","FECHANACIMIENTOPACIENTE"	,"TIPOAFILIACION","CONDICIONAFILIACIONATENCION","ACTOMEDICO","CODIGOCOBERTURA","CONDICIONPEAS",
"TOTALDEGASTOSDESCONTADOS","TOTALLIQUIDADOSIN_IGV","MOTIVOLIQUIDACION","CODIGOMECANISMOPAGO","FORMALIQUIDACION","FECHARECEPCIONFACTURACIONEPS","FECHALIQUIDACION","DECLARACIONACCIDENTETRABAJO"
,"FECHAFACTURACION"], inplace=True)
df

,RUCPRESTADOR,EPS,NRODOCUMENTO_CRYPTO,SEXO_STR,CODCIE10,FECHAINICIOPRESTACION,COD_UBIGEO,DEP,PROV,DIST,Quintil_pobreza,TOTAL_PAGADOSINIGV,EDAD
0,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-14 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,91.07,33
1,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-13 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,350.64,33
2,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,M06.9,2022-06-21 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,315.13,33
3,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,M06.9,2022-06-22 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,161.75,33
4,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-12 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,184.88,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422813,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-07-18 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,59.00,25
7422814,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-07-04 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,124.60,25
7422815,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-05-17 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,205.10,25
7422816,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-05-30 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,322.99,25
7422817,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S09.9,2022-04-11 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,524.86,25

In [179]:
grupo_enfermedad_mapping = {
    ('A00', 'B99'): 'Ciertas enfermedades infecciosas y parasitarias',
    ('C00', 'D48'): 'Neoplasias',
    ('D50', 'D89'): 'Enfermedades de la sangre y de los órganos hematopoyéticos y otros trastornos que afectan el mecanismo de la inmunidad',
    ('E00', 'E90'): 'Enfermedades endocrinas, nutricionales y metabólicas',
    ('F00', 'F99'): 'Trastornos mentales y del comportamiento',
    ('G00', 'G99'): 'Enfermedades del sistema nervioso',
    ('H00', 'H59'): 'Enfermedades del ojo y sus anexos',
    ('H60', 'H95'): 'Enfermedades del oído y de la apófisis mastoides',
    ('I00', 'I99'): 'Enfermedades del aparato circulatorio',
    ('J00', 'J99'): 'Enfermedades del aparato respiratorio',
    ('K00', 'K93'): 'Enfermedades del aparato digestivo',
    ('L00', 'L99'): 'Enfermedades de la piel y el tejido subcutáneo',
    ('M00', 'M99'): 'Enfermedades del sistema osteomuscular y del tejido conectivo',
    ('N00', 'N99'): 'Enfermedades del aparato genitourinario',
    ('O00', 'O99'): 'Embarazo, parto y puerperio',
    ('P00', 'P96'): 'Ciertas afecciones originadas en el periodo perinatal',
    ('Q00', 'Q99'): 'Malformaciones congénitas, deformidades y anomalías cromosómicas',
    ('R00', 'R99'): 'Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte',
    ('S00', 'T98'): 'Traumatismos, envenenamientos y algunas otras consecuencias de causa externa',
    ('V01', 'Y98'): 'Causas externas de morbilidad y de mortalidad',
    ('Z00', 'Z99'): 'Factores que influyen en el estado de salud y contacto con los servicios de salud',
    ('U00', 'U99'): 'Códigos para situaciones especiales'
}

def get_grupo_enfermedad(diagnostico):
    if pd.isna(diagnostico):
      #  print("nan_des")
        return 'Desconocido'
    code = diagnostico[:3]
    for (start, end), group in grupo_enfermedad_mapping.items():
        if start <= code <= end:
            return group
    #print("Desconocido NO RANGE")
    return 'Desconocido'

In [180]:
# Apply the function to the DataFrame
df['GrupoEnfermedad'] = df['CODCIE10'].apply(get_grupo_enfermedad)

# Display the DataFrame
df

,RUCPRESTADOR,EPS,NRODOCUMENTO_CRYPTO,SEXO_STR,CODCIE10,FECHAINICIOPRESTACION,COD_UBIGEO,DEP,PROV,DIST,Quintil_pobreza,TOTAL_PAGADOSINIGV,EDAD,GrupoEnfermedad
0,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-14 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,91.07,33,Enfermedades del aparato digestivo
1,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-13 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,350.64,33,Enfermedades del aparato digestivo
2,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,M06.9,2022-06-21 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,315.13,33,Enfermedades del sistema osteomuscular y del t...
3,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,M06.9,2022-06-22 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,161.75,33,Enfermedades del sistema osteomuscular y del t...
4,20228319768,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,K02.1,2022-07-12 00:00:00,150503.0,LORETO,UCAYALI,PADRE MARQUEZ,1.0,184.88,33,Enfermedades del aparato digestivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7422813,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-07-18 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,59.00,25,"Traumatismos, envenenamientos y algunas otras ..."
7422814,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-07-04 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,124.60,25,"Traumatismos, envenenamientos y algunas otras ..."
7422815,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-05-17 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,205.10,25,"Traumatismos, envenenamientos y algunas otras ..."
7422816,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S62.3,2022-05-30 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,322.99,25,"Traumatismos, envenenamientos y algunas otras ..."
7422817,20510931514,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,S09.9,2022-04-11 00:00:00,930101.0,ASIA,REPUBLICA DE COREA,SEUL,NaN,524.86,25,"Traumatismos, envenenamientos y algunas otras ..."

In [181]:
file_path = r'C:\Users\Eduardo\Desktop\HACKATONRIMAC\CATALOGO_CIE10.csv'
dfNB = pd.read_csv(file_path, encoding='utf-8')
dfNB

,CODIGOCIE10,NOMBRECIE10,SEXO,EDAD,SITUACION
0,A00.0,"Cólera debido a Vibrio cholerae 01, biotipo ch...",Ambos,Cualquiera,ACTIVO
1,A00.1,"Cólera debido a Vibrio cholerae 01, biotipo El...",Ambos,Cualquiera,ACTIVO
2,A00.9,"Cólera, no especificado",Ambos,Cualquiera,ACTIVO
3,A01.0,Fiebre tifoidea,Ambos,Cualquiera,ACTIVO
4,A01.1,Fiebre paratifoidea A,Ambos,Cualquiera,ACTIVO
...,...,...,...,...,...
12667,Z99.2,Dependencia de diálisis renal,Ambos,Cualquiera,ACTIVO
12668,Z99.3,Dependencia de silla de ruedas,Ambos,Cualquiera,ACTIVO
12669,Z99.4,DEPENDENCIA DE CORAZON ARTIFICIAL,Ambos,Cualquiera,ACTIVO
12670,Z99.8,Dependencia de otras máquinas y dispositivos c...,Ambos,Cualquiera,ACTIVO
12671,Z99.9,Dependencia de máquina y dispositivo capacitan...,Ambos,Cualquiera,ACTIVO

In [182]:
dfNB['NOMBRECIE10'] = dfNB['NOMBRECIE10'].str.replace(',', ';')
dfNB = dfNB[['CODIGOCIE10', 'NOMBRECIE10']]
dfNB

      CODIGOCIE10                                        NOMBRECIE10
0           A00.0  Cólera debido a Vibrio cholerae 01; biotipo ch...
1           A00.1  Cólera debido a Vibrio cholerae 01; biotipo El...
2           A00.9                            Cólera; no especificado
3           A01.0                                    Fiebre tifoidea
4           A01.1                              Fiebre paratifoidea A
...           ...                                                ...
12667       Z99.2                      Dependencia de diálisis renal
12668       Z99.3                     Dependencia de silla de ruedas
12669       Z99.4                  DEPENDENCIA DE CORAZON ARTIFICIAL
12670       Z99.8  Dependencia de otras máquinas y dispositivos c...
12671       Z99.9  Dependencia de máquina y dispositivo capacitan...

[12672 rows x 2 columns]

In [183]:
df_merged = pd.merge(df, dfNB, left_on='CODCIE10', right_on='CODIGOCIE10', how='left')

# Eliminar la columna duplicada CODIGOCIE10 después de la fusión, si es necesario
df_merged.drop(columns=['CODIGOCIE10'], inplace=True)

df_merged['FECHAINICIOPRESTACION'] = pd.to_datetime(df_merged['FECHAINICIOPRESTACION'])

# Formatear FECHAINICIOPRESTACION como solo fecha
df_merged['FECHAINICIOPRESTACION'] = df_merged['FECHAINICIOPRESTACION'].dt.date

df_merged.drop(columns=['Quintil_pobreza', 'COD_UBIGEO', 'CODCIE10', 'RUCPRESTADOR'], inplace=True)

df_merged

,EPS,NRODOCUMENTO_CRYPTO,SEXO_STR,FECHAINICIOPRESTACION,DEP,PROV,DIST,TOTAL_PAGADOSINIGV,EDAD,GrupoEnfermedad,NOMBRECIE10
0,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-14,LORETO,UCAYALI,PADRE MARQUEZ,91.07,33,Enfermedades del aparato digestivo,Caries de la dentina
1,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-13,LORETO,UCAYALI,PADRE MARQUEZ,350.64,33,Enfermedades del aparato digestivo,Caries de la dentina
2,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-21,LORETO,UCAYALI,PADRE MARQUEZ,315.13,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada
3,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-22,LORETO,UCAYALI,PADRE MARQUEZ,161.75,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada
4,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-12,LORETO,UCAYALI,PADRE MARQUEZ,184.88,33,Enfermedades del aparato digestivo,Caries de la dentina
...,...,...,...,...,...,...,...,...,...,...,...
7422813,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,2022-07-18,ASIA,REPUBLICA DE COREA,SEUL,59.00,25,"Traumatismos, envenenamientos y algunas otras ...",Fractura de otros huesos metacarpianos
7422814,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,2022-07-04,ASIA,REPUBLICA DE COREA,SEUL,124.60,25,"Traumatismos, envenenamientos y algunas otras ...",Fractura de otros huesos metacarpianos
7422815,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,2022-05-17,ASIA,REPUBLICA DE COREA,SEUL,205.10,25,"Traumatismos, envenenamientos y algunas otras ...",Fractura de otros huesos metacarpianos
7422816,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,2022-05-30,ASIA,REPUBLICA DE COREA,SEUL,322.99,25,"Traumatismos, envenenamientos y algunas otras ...",Fractura de otros huesos metacarpianos
7422817,Otro,53BE83C886B70D05625BB3B36E95CF8323006BCB,HOMBRE,2022-04-11,ASIA,REPUBLICA DE COREA,SEUL,524.86,25,"Traumatismos, envenenamientos y algunas otras ...",Traumatismo de la cabeza; no especificado

In [185]:
df_merged["DEP"].unique()

array(['LORETO', 'AREQUIPA', 'JUNIN', 'SAN MARTIN', 'LIMA', 'APURIMAC',
       'AMAZONAS', 'CUSCO', 'ANCASH', 'AYACUCHO', 'CAJAMARCA', 'ICA',
       'LAMBAYEQUE', 'MADRE DE DIOS', 'PUNO', 'HUANUCO', 'HUANCAVELICA',
       'LA LIBERTAD', 'PASCO', 'TACNA', 'CALLAO', 'TUMBES', 'UCAYALI',
       'MOQUEGUA', 'PIURA', 'AMERICA', 'EUROPA', 'ASIA', nan, 'AFRICA',
       'OCEANIA'], dtype=object)

In [187]:
import numpy as np
valores_a_eliminar = ['AMERICA', 'EUROPA', 'ASIA', 'AFRICA', 'OCEANIA', np.nan]
df_merged = df_merged.loc[~df_merged['DEP'].isin(valores_a_eliminar)]

df_merged['PAIS'] = 'Peru'
df_merged

,EPS,NRODOCUMENTO_CRYPTO,SEXO_STR,FECHAINICIOPRESTACION,DEP,PROV,DIST,TOTAL_PAGADOSINIGV,EDAD,GrupoEnfermedad,NOMBRECIE10
0,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-14,LORETO,UCAYALI,PADRE MARQUEZ,91.07,33,Enfermedades del aparato digestivo,Caries de la dentina
1,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-13,LORETO,UCAYALI,PADRE MARQUEZ,350.64,33,Enfermedades del aparato digestivo,Caries de la dentina
2,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-21,LORETO,UCAYALI,PADRE MARQUEZ,315.13,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada
3,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-22,LORETO,UCAYALI,PADRE MARQUEZ,161.75,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada
4,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-12,LORETO,UCAYALI,PADRE MARQUEZ,184.88,33,Enfermedades del aparato digestivo,Caries de la dentina
...,...,...,...,...,...,...,...,...,...,...,...
7422502,Otro,B046B80BEF6369B654BE7CC7FD2C0D97E12A4CAA,MUJER,2022-10-06,SAN MARTIN,TOCACHE,SANTA LUCIA,221.83,21,"Síntomas, signos y hallazgos anormales clínico...",Dolor pélvico y perineal
7422503,Otro,B046B80BEF6369B654BE7CC7FD2C0D97E12A4CAA,MUJER,2021-08-03,SAN MARTIN,TOCACHE,SANTA LUCIA,100.47,21,Enfermedades del aparato genitourinario,Hemorragia vaginal y uterina anormal; no espec...
7422504,Otro,8F75A1260D5E248F3BF383060FEF88FD3BA6FA44,MUJER,2022-10-18,SAN MARTIN,TOCACHE,SANTA LUCIA,158.12,29,Ciertas enfermedades infecciosas y parasitarias,Candidiasis de la vulva y de la vagina (N77.1*...
7422505,Otro,8F75A1260D5E248F3BF383060FEF88FD3BA6FA44,MUJER,2022-10-17,SAN MARTIN,TOCACHE,SANTA LUCIA,221.83,29,Enfermedades del aparato genitourinario,Enfermedad inflamatoria del cuello uterino
7422506,Otro,060A1F4BAB1E13F36228763C2EA768475AD20043,HOMBRE,2022-01-10,SAN MARTIN,TOCACHE,SANTA LUCIA,182.70,5,Enfermedades del aparato respiratorio,Laringitis aguda

In [188]:
df_merged['PAIS'] = 'Peru'
df_merged

,EPS,NRODOCUMENTO_CRYPTO,SEXO_STR,FECHAINICIOPRESTACION,DEP,PROV,DIST,TOTAL_PAGADOSINIGV,EDAD,GrupoEnfermedad,NOMBRECIE10,PAIS
0,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-14,LORETO,UCAYALI,PADRE MARQUEZ,91.07,33,Enfermedades del aparato digestivo,Caries de la dentina,Peru
1,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-13,LORETO,UCAYALI,PADRE MARQUEZ,350.64,33,Enfermedades del aparato digestivo,Caries de la dentina,Peru
2,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-21,LORETO,UCAYALI,PADRE MARQUEZ,315.13,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada,Peru
3,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-06-22,LORETO,UCAYALI,PADRE MARQUEZ,161.75,33,Enfermedades del sistema osteomuscular y del t...,Artritis reumatoide; no especificada,Peru
4,Otro,70D912FEFD17BE245512B5CD00D6703B24C13FD6,HOMBRE,2022-07-12,LORETO,UCAYALI,PADRE MARQUEZ,184.88,33,Enfermedades del aparato digestivo,Caries de la dentina,Peru
...,...,...,...,...,...,...,...,...,...,...,...,...
7422502,Otro,B046B80BEF6369B654BE7CC7FD2C0D97E12A4CAA,MUJER,2022-10-06,SAN MARTIN,TOCACHE,SANTA LUCIA,221.83,21,"Síntomas, signos y hallazgos anormales clínico...",Dolor pélvico y perineal,Peru
7422503,Otro,B046B80BEF6369B654BE7CC7FD2C0D97E12A4CAA,MUJER,2021-08-03,SAN MARTIN,TOCACHE,SANTA LUCIA,100.47,21,Enfermedades del aparato genitourinario,Hemorragia vaginal y uterina anormal; no espec...,Peru
7422504,Otro,8F75A1260D5E248F3BF383060FEF88FD3BA6FA44,MUJER,2022-10-18,SAN MARTIN,TOCACHE,SANTA LUCIA,158.12,29,Ciertas enfermedades infecciosas y parasitarias,Candidiasis de la vulva y de la vagina (N77.1*...,Peru
7422505,Otro,8F75A1260D5E248F3BF383060FEF88FD3BA6FA44,MUJER,2022-10-17,SAN MARTIN,TOCACHE,SANTA LUCIA,221.83,29,Enfermedades del aparato genitourinario,Enfermedad inflamatoria del cuello uterino,Peru
7422506,Otro,060A1F4BAB1E13F36228763C2EA768475AD20043,HOMBRE,2022-01-10,SAN MARTIN,TOCACHE,SANTA LUCIA,182.70,5,Enfermedades del aparato respiratorio,Laringitis aguda,Peru

In [189]:
df_merged.to_csv('EPS_PRESTACION_2022.csv', index=False)